### PR TITLE
Fix Backbone javascript errors on New Booking screens (fixes #5)

### LINKED ISSUE #5: New booking doesn't work
I am seeing JS error in console when try to do a new booking after applying this PR https://github.com/mjwconsult/civibooking/pull/3
I am on civi 5.28.4, Php 7.3

Screenshot 2020-10-18 at 13 09 45

Screenshot 2020-10-18 at 13 11 54

### PR DESCRIPTION
**Pull request by mlutfy**
ping @tapashdatta - I think this fixes the bug you raised.

Depends on #3

### CODE REVIEW

File: CRM/Booking/Form/Booking/Info.php [hunk 1]
```diff
@@ -406,15 +406,25 @@ public static function registerScripts() {
...
+      ->addScriptFile('civicrm.packages', 'backbone/backbone.collectionsubset.js', 125, 'html-header', FALSE)
+      ->addScriptFile('civicrm.packages', 'backbone-forms/distribution/backbone-forms.js', 130, 'html-header', FALSE)
+      ->addScriptFile('civicrm.packages', 'backbone-forms/distribution/adapters/backbone.bootstrap-modal.min.js', 140, 'html-header', FALSE)
+      ->addScriptFile('civicrm.packages', 'backbone-forms/distribution/editors/list.min.js', 140, 'html-header', FALSE)
+      ->addStyleFile('civicrm.packages', 'backbone-forms/distribution/templates/default.css', 140, 'html-header')
+      ->addScript('CRM.BB = Backbone.noConflict();', 300, 'html-header')
+      ->addStyleFile('civicrm', 'css/crm.designer.css', 140, 'html-header')
+      ->addScriptFile('civicrm', 'js/crm.backbone.js', 150);
+
     CRM_Core_Resources::singleton()
```
Comment (colemanw) [inline CRM/Booking/Form/Booking/Info.php:423]: Kinda weird to mix the new and old way of referring to `Civi::resources()` a few lines apart.
